# Generated by Django 2.1.1 on 2018-10-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('on_accountapi', '0002_auto_20181010_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='on_account',
            name='userid',
            field=models.ForeignKey(db_column='email', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='limit.User'),
        ),
    ]
