# Generated by Django 2.1.1 on 2018-10-11 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('on_accountapi', '0004_auto_20181010_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='on_account',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='limit.User', verbose_name='建立人員'),
        ),
    ]
