# Generated by Django 2.1.1 on 2018-10-11 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('on_accountapi', '0005_auto_20181011_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='on_account',
            name='userid',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='limit.User', verbose_name='建立人員'),
        ),
    ]
