# Generated by Django 2.1.1 on 2018-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20181005_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportrecord',
            name='sdate',
            field=models.DateField(verbose_name='運動日期'),
        ),
    ]
