# Generated by Django 2.1.1 on 2018-10-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0002_auto_20181007_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.Menu'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='menuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.Menu'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.Role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.User'),
        ),
    ]
