# Generated by Django 2.1.1 on 2018-10-09 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0003_auto_20181008_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.Menu'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='menuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.Menu'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.Role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.Role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.User'),
        ),
    ]
