# Generated by Django 2.1.1 on 2018-10-03 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('level', models.IntegerField()),
                ('index', models.IntegerField()),
                ('state', models.BooleanField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.menu')),
            ],
            options={
                'db_table': 'limit_menu',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=20, unique=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.BooleanField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'limit_role',
            },
        ),
        migrations.CreateModel(
            name='rolemenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('state', models.BooleanField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('menuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.menu')),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.role')),
            ],
            options={
                'db_table': 'limit_rolemenu',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=2)),
                ('password', models.CharField(max_length=20)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'limit_user',
            },
        ),
        migrations.CreateModel(
            name='userrole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.role')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.user')),
            ],
            options={
                'db_table': 'limit_userrole',
            },
        ),
    ]
